[package]
name = "doenetml-macros"
description = "Macros used in the Rust implementation of DoenetML's _Core_"
version = { workspace = true }
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true

[dependencies]
quote = { workspace = true }
proc-macro2 = { workspace = true }
syn = { workspace = true, features = ["visit", "visit-mut", "full"] }
convert_case = { workspace = true }
strum_macros = { workspace = true }
strum = { workspace = true }
darling = "0.20.5"
prettyplease = "0.2.16"

[lints.clippy]
# Workaround for darling https://github.com/rust-lang/rust-clippy/issues/12643  2024-07-05
manual_unwrap_or_default = "allow"
